FROM node: latest AS build
WORKDIR /app
COPY . /app

RUN npm install npm@latest -g
RUN npm install
RUN npm run build 

#._______________

# FROM ubuntu
# RUN apt-get-update
# RUN apt-get install nginx -y
# COPY --from=build /app/dist/var/www/html/
# EXPOSE 